### ISSUE TITLE
JSON loading too slow

### ISSUE THREAD

**Issue by MGF1998** [MGF1998/private_site#2]
Script additionally no longer loads questions when lagged out once.

**Comment by MGF1998** [comment]
Issue most likely identified - the entore json is re-read when choosing a new question. Maybe add a delay/event listener to wait for json, or alternatively preload entire thing and store somewhere...

**Comment by FelixRilling** [comment]
Idea: wrap everything that needs the data into the callback of the ajax call to avoid errors caused by missing data

**Comment by MGF1998** [comment]
**On hold for now** - using other projects to learn about related syntax. (cont. within 48h)

**Comment by MGF1998** [comment]
@FelixRilling rewrote jeopardy.js entirely, now it works! Thank you <3
